import { NextPage } from "next";
import Head from "next/head";

const PlayerDetail: NextPage = () => {
  return (
    <>
      <Head>
        <title>player | Chelstagram</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      PlayerDetail
    </>
  )
}

export default PlayerDetail