import { NextPage } from "next";
import Head from "next/head";

const Bookmark: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bookmark | Chelstagram</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      Bookmark
    </>
  );
};

export default Bookmark;
