import { NextPage } from "next";
import Head from "next/head";

const Players: NextPage = () => {
  return (
    <>
      <Head>
        <title>Players | Chelstagram</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      Players
    </>
  );
};

export default Players;
