import { NextPage } from "next"
import Head from "next/head"

const Talk: NextPage = () => {
  return (
    <>
      <Head>
        <title>Talk with other Blues | Chelstagram</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      Talk
    </>
  )
}

export default Talk