import { PlayerProfile } from "types/playerTypes";

export const players: PlayerProfile[] = [
  {
    id: 885461944995,
    backNumber: 1,
    name: "Kepa Arrizabalaga",
    height: '186cm',
    weight: '89kg',
    mainPosition: "GoalKeeper",
    subPosition: "GoalKeeper",
    detailPosition: ['GK'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p109745.png",
    backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_402,q_auto,w_748,z_1.0/v1/editorial/news/2021/07/29/Kepa_GettyImages-1330966814",
    birthDate: "October 3, 1994",
    birthPlace: "Spain",
    likes: 103432,
    liked: false,
    stats: {
      appearances: 4,
      assists: 0,
      chancesCreated: 0,
      cleanSheets: 2,
      conversionRate: 0,
      crosses: 0,
      gamesStarted: 4,
      goals: 0,
      goalsConceded: 2,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 180,
      minutesPlayed: 360,
      passAccuracy: 0.79,
      passesCompleted: 86,
      passesTotal: 109,
      saves: 11,
      savesPerGame: 2.75,
      shootingAccuracy: 0,
      shotsOnTarget: 0,
      shotsSaved: 0.85,
      shotsTotal: 0,
      tackleSuccess: 0,
      tacklesTotal: 0,
      tacklesWon: 0,
    },
    comments: [],
  },
  {
    id: 438122660066,
    backNumber: 2,
    name: "Antonio Rudiger",
    height: '190cm',
    weight: '86kg',
    mainPosition: "Defender",
    subPosition: "CenterBack",
    detailPosition: ['CB', 'SW'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p102380.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_north_west,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Rudiger_GettyImages-1331794166",
    birthDate: "March 3, 1993",
    birthPlace: "Germany",
    likes: 12343,
    liked: false,
    stats: {
      appearances: 23,
      assists: 0,
      chancesCreated: 11,
      cleanSheets: 9,
      conversionRate: 0.11,
      crosses: 4,
      gamesStarted: 23,
      goals: 2,
      goalsConceded: 18,
      goalsFromInsideBox: 2,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 2,
      minutesPerGoalConceded: 115,
      minutesPlayed: 2070,
      passAccuracy: 0.87,
      passesCompleted: 1368,
      passesTotal: 1570,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.37,
      shotsOnTarget: 7,
      shotsSaved: 0,
      shotsTotal: 19,
      tackleSuccess: 0.67,
      tacklesTotal: 27,
      tacklesWon: 18,
    },
    comments: [],
  },
  {
    id: 297806375874,
    backNumber: 3,
    name: "Marcos Alonso",
    height: '189cm',
    weight: '85kg',
    mainPosition: "Defender",
    subPosition: "SideBack",
    detailPosition: ['LB', 'LWB'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p82263.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/07/30/marcos_alonso_july_2021",
    birthDate: "December 28, 1990",
    birthPlace: "Spain",
    likes: 14543,
    liked: false,
    stats: {
      appearances: 18,
      assists: 2,
      chancesCreated: 21,
      cleanSheets: 4,
      conversionRate: 0.07,
      crosses: 10,
      gamesStarted: 16,
      goals: 1,
      goalsConceded: 14,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 1,
      goalsFromSetPieces: 1,
      goalsScored: 1,
      minutesPerGoalConceded: 103,
      minutesPlayed: 1435,
      passAccuracy: 0.8,
      passesCompleted: 549,
      passesTotal: 685,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.4,
      shotsOnTarget: 6,
      shotsSaved: 0,
      shotsTotal: 15,
      tackleSuccess: 0.72,
      tacklesTotal: 32,
      tacklesWon: 23,
    },
    comments: [],
  },
  {
    id: 2481013486,
    backNumber: 4,
    name: "Andreas Christensen",
    height: '188cm',
    weight: '83kg',
    mainPosition: "Defender",
    subPosition: "CenterBack",
    detailPosition: ['CB', 'SW'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p135363.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Christensen_DAZ_5208",
    birthDate: "April 10, 1996",
    birthPlace: "Denmark",
    likes: 6542,
    liked: false,
    stats: {
      appearances: 13,
      assists: 0,
      chancesCreated: 4,
      cleanSheets: 5,
      conversionRate: 0,
      crosses: 0,
      gamesStarted: 11,
      goals: 0,
      goalsConceded: 8,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 125,
      minutesPlayed: 999,
      passAccuracy: 0.88,
      passesCompleted: 739,
      passesTotal: 839,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0,
      shotsOnTarget: 0,
      shotsSaved: 0,
      shotsTotal: 3,
      tackleSuccess: 0.67,
      tacklesTotal: 6,
      tacklesWon: 4,
    },
    comments: [],
  },
  {
    id: 64961428152,
    backNumber: 5,
    name: "Jorginho",
    height: '180cm',
    weight: '68kg',
    mainPosition: "Midfielder",
    subPosition: "Defensive Midfielder",
    detailPosition: ['CDM', 'CM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p85955.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Jorginho-DAZ_5738",
    birthDate: "December 20, 1991",
    birthPlace: "Brazil",
    likes: 234321,
    liked: false,
    stats: {
      appearances: 20,
      assists: 1,
      chancesCreated: 14,
      cleanSheets: 4,
      conversionRate: 0.6,
      crosses: 0,
      gamesStarted: 17,
      goals: 6,
      goalsConceded: 13,
      goalsFromInsideBox: 6,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 6,
      minutesPerGoalConceded: 118,
      minutesPlayed: 1529,
      passAccuracy: 0.89,
      passesCompleted: 1062,
      passesTotal: 1197,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.8,
      shotsOnTarget: 8,
      shotsSaved: 0,
      shotsTotal: 10,
      tackleSuccess: 0.52,
      tacklesTotal: 42,
      tacklesWon: 22,
    },
    comments: [],
  },
  {
    id: 68658206379,
    backNumber: 6,
    name: "Thiago Silva",
    height: '181cm',
    weight: '82kg',
    mainPosition: "Defender",
    subPosition: "CenterBack",
    detailPosition: ['CB', 'SW'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p51090.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Thiago_Silva_DAZ_5496",
    birthDate: "September 22, 1984",
    birthPlace: "Brazil",
    likes: 23432,
    liked: false,
    stats: {
      appearances: 20,
      assists: 0,
      chancesCreated: 4,
      cleanSheets: 7,
      conversionRate: 0.3,
      crosses: 0,
      gamesStarted: 17,
      goals: 3,
      goalsConceded: 15,
      goalsFromInsideBox: 3,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 3,
      minutesPerGoalConceded: 110,
      minutesPlayed: 1643,
      passAccuracy: 0.92,
      passesCompleted: 1376,
      passesTotal: 1503,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.5,
      shotsOnTarget: 5,
      shotsSaved: 0,
      shotsTotal: 10,
      tackleSuccess: 0.74,
      tacklesTotal: 19,
      tacklesWon: 14,
    },
    comments: [],
  },
  {
    id: 684496001282,
    backNumber: 7,
    name: `N'Golo Kante`,
    height: '168cm',
    weight: '72kg',
    mainPosition: "Midfielder",
    subPosition: "Defensive Midfielder",
    detailPosition: ['CDM', 'CM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p116594.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Kante_GettyImages-1234159353",
    birthDate: "March 29, 1991",
    birthPlace: "France",
    likes: 43215,
    liked: false,
    stats: {
      appearances: 15,
      assists: 2,
      chancesCreated: 6,
      cleanSheets: 3,
      conversionRate: 0.33,
      crosses: 0,
      gamesStarted: 11,
      goals: 2,
      goalsConceded: 9,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 2,
      goalsFromSetPieces: 0,
      goalsScored: 2,
      minutesPerGoalConceded: 107,
      minutesPlayed: 960,
      passAccuracy: 0.85,
      passesCompleted: 563,
      passesTotal: 660,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.67,
      shotsOnTarget: 4,
      shotsSaved: 0,
      shotsTotal: 6,
      tackleSuccess: 0.43,
      tacklesTotal: 30,
      tacklesWon: 13,
    },
    comments: [],
  },
  {
    id: 330922720107,
    backNumber: 8,
    name: `Mateo Kovacic`,
    height: '176cm',
    weight: '82kg',
    mainPosition: "Midfielder",
    subPosition: "Defensive Midfielder",
    detailPosition: ['CDM', 'CM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p91651.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Kovacic_GettyImages-1234386075",
    birthDate: "May 6, 1994",
    birthPlace: "Austria",
    likes: 12343,
    liked: false,
    stats: {
      appearances: 16,
      assists: 5,
      chancesCreated: 13,
      cleanSheets: 5,
      conversionRate: 0.15,
      crosses: 0,
      gamesStarted: 12,
      goals: 2,
      goalsConceded: 6,
      goalsFromInsideBox: 1,
      goalsFromOutsideBox: 1,
      goalsFromSetPieces: 0,
      goalsScored: 2,
      minutesPerGoalConceded: 188,
      minutesPlayed: 1127,
      passAccuracy: 0.87,
      passesCompleted: 725,
      passesTotal: 829,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.31,
      shotsOnTarget: 4,
      shotsSaved: 0,
      shotsTotal: 13,
      tackleSuccess: 0.63,
      tacklesTotal: 40,
      tacklesWon: 25,
    },
    comments: [],
  },
  {
    id: 79384560331,
    backNumber: 9,
    name: `Romelu Lukaku`,
    height: '191cm',
    weight: '103kg',
    mainPosition: "Forward",
    subPosition: "Striker",
    detailPosition: ['ST', 'CF'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p66749.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_north_west,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/08/18/Lukaku_fans_DTW_0676",
    birthDate: "May 13, 1993",
    birthPlace: "Belgium",
    likes: 43221,
    liked: false,
    stats: {
      appearances: 16,
      assists: 0,
      chancesCreated: 16,
      cleanSheets: 4,
      conversionRate: 0.26,
      crosses: 0,
      gamesStarted: 11,
      goals: 5,
      goalsConceded: 8,
      goalsFromInsideBox: 5,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 5,
      minutesPerGoalConceded: 136,
      minutesPlayed: 1088,
      passAccuracy: 0.72,
      passesCompleted: 157,
      passesTotal: 218,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.58,
      shotsOnTarget: 11,
      shotsSaved: 0,
      shotsTotal: 19,
      tackleSuccess: 0,
      tacklesTotal: 1,
      tacklesWon: 0,
    },
    comments: [],
  },
  {
    id: 186089015534,
    backNumber: 10,
    name: `Christian Pulisic`,
    height: '177cm',
    weight: '73kg',
    mainPosition: "Forward",
    subPosition: "WingForward",
    detailPosition: ['LW', 'LM', 'RW', 'RM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p176413.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Pulisic_GettyImages-1234385345",
    birthDate: "September 18, 1998",
    birthPlace: "United States",
    likes: 12342,
    liked: false,
    stats: {
      appearances: 12,
      assists: 0,
      chancesCreated: 8,
      cleanSheets: 1,
      conversionRate: 0.25,
      crosses: 1,
      gamesStarted: 8,
      goals: 3,
      goalsConceded: 7,
      goalsFromInsideBox: 3,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 3,
      minutesPerGoalConceded: 108,
      minutesPlayed: 754,
      passAccuracy: 0.8,
      passesCompleted: 185,
      passesTotal: 231,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.58,
      shotsOnTarget: 7,
      shotsSaved: 0,
      shotsTotal: 12,
      tackleSuccess: 0.75,
      tacklesTotal: 4,
      tacklesWon: 3,
    },
    comments: [],
  },
  {
    id: 357216531383,
    backNumber: 11,
    name: `Timo Werner`,
    height: '180cm',
    weight: '75kg',
    mainPosition: "Forward",
    subPosition: "Striker",
    detailPosition: ['ST', 'CF', 'LW'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p165153.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Werner_GettyImages-1331791190",
    birthDate: "March 6, 1996",
    birthPlace: "Germany",
    likes: 23412,
    liked: false,
    stats: {
      appearances: 11,
      assists: 1,
      chancesCreated: 1,
      cleanSheets: 2,
      conversionRate: 0.1,
      crosses: 0,
      gamesStarted: 6,
      goals: 1,
      goalsConceded: 5,
      goalsFromInsideBox: 1,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 1,
      minutesPerGoalConceded: 115,
      minutesPlayed: 576,
      passAccuracy: 0.75,
      passesCompleted: 104,
      passesTotal: 138,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.6,
      shotsOnTarget: 6,
      shotsSaved: 0,
      shotsTotal: 10,
      tackleSuccess: 0,
      tacklesTotal: 3,
      tacklesWon: 0,
    },
    comments: [],
  },
  {
    id: 584549723980,
    backNumber: 12,
    name: `Ruben Loftus-Cheek`,
    height: '191cm',
    weight: '90kg',
    mainPosition: "Midfielder",
    subPosition: "Attacking Midfielder",
    detailPosition: ['CAM', 'CM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p126187.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Loftus-Cheek_GettyImages-1331806687",
    birthDate: "January 23, 1996",
    birthPlace: "England",
    likes: 3421,
    liked: false,
    stats: {
      appearances: 12,
      assists: 2,
      chancesCreated: 4,
      cleanSheets: 1,
      conversionRate: 0,
      crosses: 1,
      gamesStarted: 7,
      goals: 0,
      goalsConceded: 9,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 77,
      minutesPlayed: 694,
      passAccuracy: 0.88,
      passesCompleted: 386,
      passesTotal: 440,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.38,
      shotsOnTarget: 3,
      shotsSaved: 0,
      shotsTotal: 8,
      tackleSuccess: 0.17,
      tacklesTotal: 12,
      tacklesWon: 2,
    },
    comments: [],
  },
  {
    id: 1479030384752,
    backNumber: 13,
    name: `Marcus Bettineli`,
    height: '193cm',
    weight: '91kg',
    mainPosition: "GoalKeeper",
    subPosition: "GoalKeeper",
    detailPosition: ['GK'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p122074.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Bettinelli_GettyImages-1234297653",
    birthDate: "May 24, 1992",
    birthPlace: "England",
    likes: 4312,
    liked: false,
    stats: {
      appearances: 1,
      assists: 0,
      chancesCreated: 0,
      cleanSheets: 0,
      conversionRate: 0,
      crosses: 0,
      gamesStarted: 1,
      goals: 0,
      goalsConceded: 1,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 90,
      minutesPlayed: 90,
      passAccuracy: 0.96,
      passesCompleted: 22,
      passesTotal: 23,
      saves: 2,
      savesPerGame: 2,
      shootingAccuracy: 0,
      shotsOnTarget: 0,
      shotsSaved: 0.67,
      shotsTotal: 0,
      tackleSuccess: 0,
      tacklesTotal: 0,
      tacklesWon: 0,
    },
    comments: [],
  },
  {
    id: 129802580761,
    backNumber: 14,
    name: `Trevoh Chalobah`,
    height: '190cm',
    weight: '82kg',
    mainPosition: "Defender",
    subPosition: "CenterBack",
    detailPosition: ['CB', 'CDM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p180736.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_560,q_auto,w_1170,z_1.0/v1/editorial/match-reports/2021-22/villarreal-super-cup/Chalobah_GettyImages-1234624597",
    birthDate: "July 5, 1999",
    birthPlace: "England",
    likes: 12345,
    liked: false,
    stats: {
      appearances: 14,
      assists: 0,
      chancesCreated: 1,
      cleanSheets: 5,
      conversionRate: 0.5,
      crosses: 0,
      gamesStarted: 11,
      goals: 2,
      goalsConceded: 7,
      goalsFromInsideBox: 1,
      goalsFromOutsideBox: 1,
      goalsFromSetPieces: 0,
      goalsScored: 2,
      minutesPerGoalConceded: 130,
      minutesPlayed: 909,
      passAccuracy: 0.89,
      passesCompleted: 620,
      passesTotal: 699,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.75,
      shotsOnTarget: 3,
      shotsSaved: 0,
      shotsTotal: 4,
      tackleSuccess: 0.55,
      tacklesTotal: 22,
      tacklesWon: 12,
    },
    comments: [],
  },
  {
    id: 707970602401,
    backNumber: 16,
    name: `Edouard Mendy`,
    height: '194cm',
    weight: '93kg',
    mainPosition: "GoalKeeper",
    subPosition: "GoalKeeper",
    detailPosition: ['GK'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p228286.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/07/29/Mendy_DAZ_4716-2403373_2021072790601445",
    birthDate: "March 1, 1992",
    birthPlace: "France",
    likes: 33451,
    liked: false,
    stats: {
      appearances: 20,
      assists: 0,
      chancesCreated: 0,
      cleanSheets: 8,
      conversionRate: 0,
      crosses: 0,
      gamesStarted: 20,
      goals: 0,
      goalsConceded: 16,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 113,
      minutesPlayed: 1800,
      passAccuracy: 0.8,
      passesCompleted: 377,
      passesTotal: 469,
      saves: 55,
      savesPerGame: 2.75,
      shootingAccuracy: 0,
      shotsOnTarget: 0,
      shotsSaved: 0.77,
      shotsTotal: 0,
      tackleSuccess: 0,
      tacklesTotal: 1,
      tacklesWon: 0,
    },
    comments: [],
  },
  {
    id: 237005584116,
    backNumber: 17,
    name: `Saul Niguez`,
    height: '183cm',
    weight: '77kg',
    mainPosition: "Midfielder",
    subPosition: "Defensive Midfielder",
    detailPosition: ['CDM', 'CM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p89335.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/09/01/saul-arrival-1",
    birthDate: "November 21, 1994",
    birthPlace: "Spain",
    likes: 33223,
    liked: false,
    stats: {
      appearances: 6,
      assists: 0,
      chancesCreated: 0,
      cleanSheets: 0,
      conversionRate: 0,
      crosses: 0,
      gamesStarted: 2,
      goals: 0,
      goalsConceded: 2,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 82,
      minutesPlayed: 163,
      passAccuracy: 0.86,
      passesCompleted: 105,
      passesTotal: 122,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0,
      shotsOnTarget: 0,
      shotsSaved: 0,
      shotsTotal: 1,
      tackleSuccess: 0.4,
      tacklesTotal: 5,
      tacklesWon: 2,
    },
    comments: [],
  },
  {
    id: 391111946750,
    backNumber: 18,
    name: `Ross Barkley`,
    height: '185cm',
    weight: '87kg',
    mainPosition: "Midfielder",
    subPosition: "Attacking Midfielder",
    detailPosition: ['CAM', 'CM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p88894.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/07/29/Barkley_DTW_9757_20210717112457709",
    birthDate: "December 5, 1993",
    birthPlace: "England",
    likes: 1532,
    liked: false,
    stats: {
      appearances: 5,
      assists: 0,
      chancesCreated: 7,
      cleanSheets: 0,
      conversionRate: 0,
      crosses: 0,
      gamesStarted: 1,
      goals: 0,
      goalsConceded: 1,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 151,
      minutesPlayed: 151,
      passAccuracy: 0.85,
      passesCompleted: 88,
      passesTotal: 104,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.2,
      shotsOnTarget: 1,
      shotsSaved: 0,
      shotsTotal: 5,
      tackleSuccess: 0,
      tacklesTotal: 0,
      tacklesWon: 0,
    },
    comments: [],
  },
  {
    id: 1333556259636,
    backNumber: 19,
    name: `Mason Mount`,
    height: '180cm',
    weight: '74kg',
    mainPosition: "Midfielder",
    subPosition: "Attacking Midfielder",
    detailPosition: ['CAM', 'LM', 'RM', 'LW', 'RW'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p184341.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Mount_DAZ_5506",
    birthDate: "January 10, 1999",
    birthPlace: "England",
    likes: 663212,
    liked: false,
    stats: {
      appearances: 21,
      assists: 6,
      chancesCreated: 28,
      cleanSheets: 4,
      conversionRate: 0.24,
      crosses: 9,
      gamesStarted: 16,
      goals: 7,
      goalsConceded: 13,
      goalsFromInsideBox: 6,
      goalsFromOutsideBox: 1,
      goalsFromSetPieces: 0,
      goalsScored: 7,
      minutesPerGoalConceded: 110,
      minutesPlayed: 1435,
      passAccuracy: 0.84,
      passesCompleted: 509,
      passesTotal: 603,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.69,
      shotsOnTarget: 20,
      shotsSaved: 0,
      shotsTotal: 29,
      tackleSuccess: 0.44,
      tacklesTotal: 27,
      tacklesWon: 12,
    },
    comments: [
      {
        playerId: 1333556259636,
        id: 230299278072,
        userId: 149765870964,
        nickname: "조진호",
        profileImg: null,
        text: "댓글 작성 완료",
        createdAt: '2022-02-08 12:00:00',
        modifiedAt: '2022-02-08 13:00:01',
      },
    ],
  },
  {
    id: 1085445895612,
    backNumber: 20,
    name: `Callum Hudson-Odoi`,
    height: '178cm',
    weight: '78kg',
    mainPosition: "Forward",
    subPosition: "WingForward",
    detailPosition: ['LW', 'RW'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p209046.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Hudson-Odoi_DAZ_2077",
    birthDate: "November 7, 2000",
    birthPlace: "England",
    likes: 4321,
    liked: false,
    stats: {
      appearances: 15,
      assists: 2,
      chancesCreated: 23,
      cleanSheets: 1,
      conversionRate: 0.08,
      crosses: 5,
      gamesStarted: 11,
      goals: 1,
      goalsConceded: 8,
      goalsFromInsideBox: 1,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 1,
      minutesPerGoalConceded: 121,
      minutesPlayed: 966,
      passAccuracy: 0.85,
      passesCompleted: 302,
      passesTotal: 354,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.58,
      shotsOnTarget: 7,
      shotsSaved: 0,
      shotsTotal: 12,
      tackleSuccess: 0.71,
      tacklesTotal: 14,
      tacklesWon: 10,
    },
    comments: [],
  },
  {
    id: 43086832862,
    backNumber: 21,
    name: `Ben Chilwell`,
    height: '180cm',
    weight: '78kg',
    mainPosition: "Defender",
    subPosition: "SideBack",
    detailPosition: ['LB', 'LWB'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p172850.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Chilwell_DAZ_5618",
    birthDate: "December 21, 1996",
    birthPlace: "England",
    likes: 22531,
    liked: false,
    stats: {
      appearances: 6,
      assists: 1,
      chancesCreated: 9,
      cleanSheets: 4,
      conversionRate: 0.33,
      crosses: 1,
      gamesStarted: 6,
      goals: 3,
      goalsConceded: 2,
      goalsFromInsideBox: 3,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 3,
      minutesPerGoalConceded: 270,
      minutesPlayed: 540,
      passAccuracy: 0.83,
      passesCompleted: 223,
      passesTotal: 269,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.67,
      shotsOnTarget: 6,
      shotsSaved: 0,
      shotsTotal: 9,
      tackleSuccess: 0.38,
      tacklesTotal: 8,
      tacklesWon: 3,
    },
    comments: [],
  },
  {
    id: 104889225255,
    backNumber: 22,
    name: `Hakim Ziyech`,
    height: '180cm',
    weight: '70kg',
    mainPosition: "Forward",
    subPosition: "WingForward",
    detailPosition: ['RW', 'RM', 'LW', 'LM'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p124183.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Ziyech_GettyImages-1330964065",
    birthDate: "March 19, 1993",
    birthPlace: "Netherlands",
    likes: 53321,
    liked: false,
    stats: {
      appearances: 13,
      assists: 2,
      chancesCreated: 14,
      cleanSheets: 1,
      conversionRate: 0.12,
      crosses: 4,
      gamesStarted: 9,
      goals: 3,
      goalsConceded: 5,
      goalsFromInsideBox: 1,
      goalsFromOutsideBox: 2,
      goalsFromSetPieces: 0,
      goalsScored: 3,
      minutesPerGoalConceded: 157,
      minutesPlayed: 787,
      passAccuracy: 0.78,
      passesCompleted: 278,
      passesTotal: 358,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.52,
      shotsOnTarget: 13,
      shotsSaved: 0,
      shotsTotal: 25,
      tackleSuccess: 0.54,
      tacklesTotal: 13,
      tacklesWon: 7,
    },
    comments: [],
  },
  {
    id: 9287066544,
    backNumber: 24,
    name: `Reece James`,
    height: '179cm',
    weight: '91kg',
    mainPosition: "Defender",
    subPosition: "SideBack",
    detailPosition: ['RB', 'RWB'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p225796.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/James_DTW_5767",
    birthDate: "December 8, 1999",
    birthPlace: "England",
    likes: 43321,
    liked: false,
    stats: {
      appearances: 16,
      assists: 5,
      chancesCreated: 26,
      cleanSheets: 5,
      conversionRate: 0.27,
      crosses: 11,
      gamesStarted: 14,
      goals: 4,
      goalsConceded: 9,
      goalsFromInsideBox: 4,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 4,
      minutesPerGoalConceded: 124,
      minutesPlayed: 1115,
      passAccuracy: 0.88,
      passesCompleted: 638,
      passesTotal: 727,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.47,
      shotsOnTarget: 7,
      shotsSaved: 0,
      shotsTotal: 15,
      tackleSuccess: 0.84,
      tacklesTotal: 19,
      tacklesWon: 16,
    },
    comments: [],
  },
  {
    id: 225241731598,
    backNumber: 28,
    name: `Cesar Azpilicueta`,
    height: '178cm',
    weight: '78kg',
    mainPosition: "Defender",
    subPosition: "SideBack",
    detailPosition: ['RB', 'RWB', 'CB', 'LB', 'LWB'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p41328.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Azpilicueta_DAZ_5248",
    birthDate: "August 29, 1989",
    birthPlace: "Spain",
    likes: 65321,
    liked: false,
    stats: {
      appearances: 17,
      assists: 2,
      chancesCreated: 11,
      cleanSheets: 4,
      conversionRate: 0,
      crosses: 4,
      gamesStarted: 16,
      goals: 0,
      goalsConceded: 11,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 127,
      minutesPlayed: 1394,
      passAccuracy: 0.84,
      passesCompleted: 831,
      passesTotal: 990,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.33,
      shotsOnTarget: 2,
      shotsSaved: 0,
      shotsTotal: 6,
      tackleSuccess: 0.54,
      tacklesTotal: 41,
      tacklesWon: 22,
    },
    comments: [],
  },
  {
    id: 100474563037,
    backNumber: 29,
    name: `Kai Havertz`,
    height: '190cm',
    weight: '83kg',
    mainPosition: "Forward",
    subPosition: "WingForward",
    detailPosition: ['RW', 'LW', 'ST', 'CF'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p219847.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Havertz_GettyImages-1234385546",
    birthDate: "June 11, 1999",
    birthPlace: "Germany",
    likes: 55321,
    liked: false,
    stats: {
      appearances: 16,
      assists: 1,
      chancesCreated: 3,
      cleanSheets: 1,
      conversionRate: 0.14,
      crosses: 2,
      gamesStarted: 12,
      goals: 2,
      goalsConceded: 8,
      goalsFromInsideBox: 2,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 2,
      minutesPerGoalConceded: 118,
      minutesPlayed: 946,
      passAccuracy: 0.83,
      passesCompleted: 264,
      passesTotal: 319,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0.57,
      shotsOnTarget: 8,
      shotsSaved: 0,
      shotsTotal: 14,
      tackleSuccess: 0.38,
      tacklesTotal: 8,
      tacklesWon: 3,
    },
    comments: [],
  },
  {
    id: 223722841199,
    backNumber: 31,
    name: `Malang Sarr`,
    height: '182cm',
    weight: '72kg',
    mainPosition: "Defender",
    subPosition: "CenterBack",
    detailPosition: ['CB'],
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p204727.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_560,q_auto,w_1170,z_1.0/v1/chelsea-app/Sarr-DAZ_2142",
    birthDate: "January 23, 1999",
    birthPlace: "France",
    likes: 2227,
    liked: false,
    stats: {
      appearances: 3,
      assists: 0,
      chancesCreated: 0,
      cleanSheets: 2,
      conversionRate: 0,
      crosses: 0,
      gamesStarted: 3,
      goals: 0,
      goalsConceded: 1,
      goalsFromInsideBox: 0,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      goalsScored: 0,
      minutesPerGoalConceded: 270,
      minutesPlayed: 270,
      passAccuracy: 0.89,
      passesCompleted: 185,
      passesTotal: 209,
      saves: 0,
      savesPerGame: 0,
      shootingAccuracy: 0,
      shotsOnTarget: 0,
      shotsSaved: 0,
      shotsTotal: 0,
      tackleSuccess: 0.83,
      tacklesTotal: 6,
      tacklesWon: 5,
    },
    comments: [],
  },
];
