import { PlayerProfile } from "types/playerTypes";

export const players: PlayerProfile[] = [
  {
    playerId: "1",
    backNumber: 1,
    playerName: "Kepa Arrizabalaga",
    position: "GoalKeeper",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p109745.png",
    backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_402,q_auto,w_748,z_1.0/v1/editorial/news/2021/07/29/Kepa_GettyImages-1330966814",
    birthDate: "October 3, 1994",
    birthPlace: "Spain",
    stats: {
      appearances: 3,
      minutesPlayed: 270,
      gamesStarted: 3,
      goals: 0,
      goalsConceded: 2,
      cleanSheets: 1,
      minsPerGoalConceded: 135,
      shotsSaved: 80,
      saves: 8,
      savesPerGame: 2.67,
    },
    comments: [],
  },
  {
    playerId: "2",
    backNumber: 2,
    playerName: "Antonio Rudiger",
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p102380.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_north_west,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Rudiger_GettyImages-1331794166",
    birthDate: "March 3, 1993",
    birthPlace: "Germany",
    stats: {
      appearances: 22,
      minutesPlayed: 1980,
      gamesStarted: 22,
      goals: 2,
      assists: 0,
      crosses: 4,
      chancesCreated: 11,
      tackleSuccess: 67,
      totalTackles: 27,
      tacklesWon: 18,
    },
    comments: [],
  },
  {
    playerId: "3",
    backNumber: 3,
    playerName: "Marcos Alonso",
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p82263.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/07/30/marcos_alonso_july_2021",
    birthDate: "December 28, 1990",
    birthPlace: "Spain",
    stats: {
      appearances: 17,
      minutesPlayed: 1432,
      gamesStarted: 16,
      goals: 1,
      assists: 2,
      crosses: 10,
      chancesCreated: 21,
      tackleSuccess: 72,
      totalTackles: 32,
      tacklesWon: 23,
    },
    comments: [],
  },
  {
    playerId: "4",
    backNumber: 4,
    playerName: "Andreas Christensen",
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p135363.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Christensen_DAZ_5208",
    birthDate: "April 10, 1996",
    birthPlace: "Denmark",
    stats: {
      appearances: 13,
      minutesPlayed: 999,
      gamesStarted: 11,
      goals: 0,
      assists: 0,
      crosses: 0,
      chancesCreated: 4,
      tackleSuccess: 67,
      totalTackles: 6,
      tacklesWon: 4,
    },
    comments: [],
  },
  {
    playerId: "5",
    backNumber: 5,
    playerName: "Jorginho",
    position: "Midfielder",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p85955.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Jorginho-DAZ_5738",
    birthDate: "December 20, 1991",
    birthPlace: "Brazil",
    stats: {
      appearances: 19,
      minutesPlayed: 1456,
      gamesStarted: 16,
      goals: 6,
      assists: 1,
      crosses: 0,
      chancesCreated: 13,
      passAccuracy: 89,
      totalPasses: 1146,
      passesCompleted: 1018,
    },
    comments: [],
  },
  {
    playerId: "6",
    backNumber: 6,
    playerName: "Thiago Silva",
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p51090.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Thiago_Silva_DAZ_5496",
    birthDate: "September 22, 1984",
    birthPlace: "Brazil",
    stats: {
      appearances: 19,
      minutesPlayed: 1553,
      gamesStarted: 16,
      goals: 2,
      assists: 0,
      crosses: 0,
      chancesCreated: 4,
      tackleSuccess: 74,
      totalTackles: 19,
      tacklesWon: 14,
    },
    comments: [],
  },
  {
    playerId: "7",
    backNumber: 7,
    playerName: `N'Golo Kante`,
    position: "Midfielder",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p116594.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Kante_GettyImages-1234159353",
    birthDate: "March 29, 1991",
    birthPlace: "France",
    stats: {
      appearances: 14,
      minutesPlayed: 943,
      gamesStarted: 11,
      goals: 2,
      assists: 2,
      crosses: 0,
      chancesCreated: 6,
      passAccuracy: 86,
      totalPasses: 639,
      passesCompleted: 548,
    },
    comments: [],
  },
  {
    playerId: "8",
    backNumber: 8,
    playerName: `Mateo Kovacic`,
    position: "Midfielder",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p91651.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Kovacic_GettyImages-1234386075",
    birthDate: "May 6, 1994",
    birthPlace: "Austria",
    stats: {
      appearances: 15,
      minutesPlayed: 1037,
      gamesStarted: 11,
      goals: 2,
      assists: 5,
      crosses: 0,
      chancesCreated: 11,
      passAccuracy: 88,
      totalPasses: 774,
      passesCompleted: 680,
    },
    comments: [],
  },
  {
    playerId: "9",
    backNumber: 9,
    playerName: `Romelu Lukaku`,
    position: "Forward",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p66749.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_north_west,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/08/18/Lukaku_fans_DTW_0676",
    birthDate: "May 13, 1993",
    birthPlace: "Belgium",
    stats: {
      appearances: 15,
      minutesPlayed: 998,
      gamesStarted: 10,
      goals: 5,
      assists: 0,
      goalsFromInsideBox: 5,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      conversionRate: 29,
      totalShots: 17,
      shotsOnTarget: 10,
      shootingAcuuracy: 59,
    },
    comments: [],
  },
  {
    playerId: "10",
    backNumber: 10,
    playerName: `Christian Pulisic`,
    position: "Forward",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p176413.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Pulisic_GettyImages-1234385345",
    birthDate: "September 18, 1998",
    birthPlace: "United States",
    stats: {
      appearances: 12,
      minutesPlayed: 754,
      gamesStarted: 8,
      goals: 3,
      assists: 0,
      crosses: 1,
      chancesCreated: 8,
      passAccuracy: 80,
      totalPasses: 231,
      passesCompleted: 185,
    },
    comments: [],
  },
  {
    playerId: "11",
    backNumber: 11,
    playerName: `Timo Werner`,
    position: "Forward",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p165153.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Werner_GettyImages-1331791190",
    birthDate: "March 6, 1996",
    birthPlace: "Germany",
    stats: {
      appearances: 11,
      minutesPlayed: 576,
      gamesStarted: 6,
      goals: 1,
      assists: 1,
      goalsFromInsideBox: 1,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      conversionRate: 10,
      totalShots: 10,
      shotsOnTarget: 6,
      shootingAcuuracy: 60,
    },
    comments: [],
  },
  {
    playerId: "12",
    backNumber: 12,
    playerName: `Ruben Loftus-Cheek`,
    position: "Midfielder",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p126187.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Loftus-Cheek_GettyImages-1331806687",
    birthDate: "January 23, 1996",
    birthPlace: "England",
    stats: {
      appearances: 12,
      minutesPlayed: 694,
      gamesStarted: 7,
      goals: 0,
      assists: 2,
      crosses: 1,
      chancesCreated: 4,
      passAccuracy: 88,
      totalPasses: 440,
      passesCompleted: 386,
    },
    comments: [],
  },
  {
    playerId: "13",
    backNumber: 13,
    playerName: `Marcus Bettineli`,
    position: "GoalKeeper",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p122074.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Bettinelli_GettyImages-1234297653",
    birthDate: "May 24, 1992",
    birthPlace: "England",
    stats: {
      appearances: 1,
      minutesPlayed: 90,
      gamesStarted: 1,
      goals: 0,
      goalsConceded: 1,
      cleanSheets: 0,
      minsPerGoalConceded: 90,
      shotsSaved: 67,
      saves: 2,
      savesPerGame: 2,
    },
    comments: [],
  },
  {
    playerId: "14",
    backNumber: 14,
    playerName: `Trevoh Chalobah`,
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p180736.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_560,q_auto,w_1170,z_1.0/v1/editorial/match-reports/2021-22/villarreal-super-cup/Chalobah_GettyImages-1234624597",
    birthDate: "July 5, 1999",
    birthPlace: "England",
    stats: {
      appearances: 14,
      minutesPlayed: 909,
      gamesStarted: 11,
      goals: 2,
      assists: 0,
      crosses: 0,
      chancesCreated: 1,
      tackleSuccess: 55,
      totalTackles: 22,
      tacklesWon: 12,
    },
    comments: [],
  },
  {
    playerId: "16",
    backNumber: 16,
    playerName: `Edouard Mendy`,
    position: "GoalKeeper",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p228286.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/07/29/Mendy_DAZ_4716-2403373_2021072790601445",
    birthDate: "March 1, 1992",
    birthPlace: "France",
    stats: {
      appearances: 20,
      minutesPlayed: 1800,
      gamesStarted: 20,
      goals: 0,
      goalsConceded: 16,
      cleanSheets: 8,
      minsPerGoalConceded: 113,
      shotsSaved: 77,
      saves: 55,
      savesPerGame: 2.75,
    },
    comments: [],
  },
  {
    playerId: "17",
    backNumber: 17,
    playerName: `Saul Niguez`,
    position: "Midfielder",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p89335.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/09/01/saul-arrival-1",
    birthDate: "November 21, 1994",
    birthPlace: "Spain",
    stats: {
      appearances: 5,
      minutesPlayed: 162,
      gamesStarted: 2,
      goals: 0,
      assists: 0,
      crosses: 0,
      chancesCreated: 0,
      passAccuracy: 86,
      totalPasses: 121,
      passesCompleted: 104,
    },
    comments: [],
  },
  {
    playerId: "18",
    backNumber: 18,
    playerName: `Ross Barkley`,
    position: "Midfielder",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p88894.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/news/2021/07/29/Barkley_DTW_9757_20210717112457709",
    birthDate: "December 5, 1993",
    birthPlace: "England",
    stats: {
      appearances: 5,
      minutesPlayed: 151,
      gamesStarted: 1,
      goals: 0,
      assists: 0,
      crosses: 0,
      chancesCreated: 7,
      passAccuracy: 85,
      totalPasses: 104,
      passesCompleted: 88,
    },
    comments: [],
  },
  {
    playerId: "19",
    backNumber: 19,
    playerName: `Mason Mount`,
    position: "Midfielder",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p184341.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Mount_DAZ_5506",
    birthDate: "January 10, 1999",
    birthPlace: "England",
    stats: {
      appearances: 20,
      minutesPlayed: 1345,
      gamesStarted: 15,
      goals: 7,
      assists: 5,
      crosses: 7,
      chancesCreated: 25,
      passAccuracy: 84,
      totalPasses: 573,
      passesCompleted: 482,
    },
    comments: [
      {
        commentId: "0a689b17-add8-4ad9-8108-18b12f68f009",
        userId: "cead7ff6-bcbf-4f1a-87ad-42756c40932d",
        userName: "조진호",
        profileImg: null,
        text: "댓글 작성 완료",
        date: 1642814456680,
      },
    ],
  },
  {
    playerId: "20",
    backNumber: 20,
    playerName: `Callum Hudson-Odoi`,
    position: "Forward",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p209046.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Hudson-Odoi_DAZ_2077",
    birthDate: "November 7, 2000",
    birthPlace: "England",
    stats: {
      appearances: 14,
      minutesPlayed: 879,
      gamesStarted: 10,
      goals: 1,
      assists: 1,
      goalsFromInsideBox: 1,
      goalsFromOutsideBox: 0,
      goalsFromSetPieces: 0,
      conversionRate: 9,
      totalShots: 11,
      shotsOnTarget: 7,
      shootingAcuuracy: 64,
    },
    comments: [],
  },
  {
    playerId: "21",
    backNumber: 21,
    playerName: `Ben Chilwell`,
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p172850.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Chilwell_DAZ_5618",
    birthDate: "December 21, 1996",
    birthPlace: "England",
    stats: {
      appearances: 6,
      minutesPlayed: 540,
      gamesStarted: 6,
      goals: 3,
      assists: 1,
      crosses: 1,
      chancesCreated: 9,
      tackleSuccess: 38,
      totalTackles: 8,
      tacklesWon: 3,
    },
    comments: [],
  },
  {
    playerId: "22",
    backNumber: 22,
    playerName: `Hakim Ziyech`,
    position: "Forward",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p124183.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Ziyech_GettyImages-1330964065",
    birthDate: "March 19, 1993",
    birthPlace: "Netherlands",
    stats: {
      appearances: 12,
      minutesPlayed: 698,
      gamesStarted: 8,
      goals: 2,
      assists: 2,
      crosses: 4,
      chancesCreated: 12,
      passAccuracy: 79,
      totalPasses: 295,
      passesCompleted: 233,
    },
    comments: [],
  },
  {
    playerId: "24",
    backNumber: 24,
    playerName: `Reece James`,
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p225796.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/James_DTW_5767",
    birthDate: "December 8, 1999",
    birthPlace: "England",
    stats: {
      appearances: 16,
      minutesPlayed: 1115,
      gamesStarted: 14,
      goals: 4,
      assists: 5,
      crosses: 11,
      chancesCreated: 26,
      tackleSuccess: 84,
      totalTackles: 19,
      tacklesWon: 16,
    },
    comments: [],
  },
  {
    playerId: "28",
    backNumber: 28,
    playerName: `Cesar Azpilicueta`,
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p41328.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Azpilicueta_DAZ_5248",
    birthDate: "August 29, 1989",
    birthPlace: "Spain",
    stats: {
      appearances: 16,
      minutesPlayed: 1304,
      gamesStarted: 15,
      goals: 0,
      assists: 2,
      crosses: 4,
      chancesCreated: 9,
      tackleSuccess: 53,
      totalTackles: 38,
      tacklesWon: 20,
    },
    comments: [],
  },
  {
    playerId: "29",
    backNumber: 29,
    playerName: `Kai Havertz`,
    position: "Forward",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p219847.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_face,h_560,q_auto,w_1170,z_1.0/v1/editorial/people/first-team/2021-22/hero/Havertz_GettyImages-1234385546",
    birthDate: "June 11, 1999",
    birthPlace: "Germany",
    stats: {
      appearances: 16,
      minutesPlayed: 946,
      gamesStarted: 12,
      goals: 2,
      assists: 1,
      crosses: 2,
      chancesCreated: 3,
      passAccuracy: 83,
      totalPasses: 319,
      passesCompleted: 264,
    },
    comments: [],
  },
  {
    playerId: "31",
    backNumber: 31,
    playerName: `Malang Sarr`,
    position: "Defender",
    profileImg:
      "https://resources.premierleague.com/premierleague/photos/players/250x250/p204727.png",
      backgroundImg:
      "https://res.cloudinary.com/chelsea-production/image/upload/c_fill,dpr_auto,f_auto,fl_lossy,g_auto,h_560,q_auto,w_1170,z_1.0/v1/chelsea-app/Sarr-DAZ_2142",
    birthDate: "January 23, 1999",
    birthPlace: "France",
    stats: {
      appearances: 2,
      minutesPlayed: 180,
      gamesStarted: 2,
      goals: 0,
      assists: 0,
      crosses: 0,
      chancesCreated: 0,
      tackleSuccess: 83,
      totalTackles: 6,
      tacklesWon: 5,
    },
    comments: [],
  },
];
